export const CharacterSchema = {
  creatorUserId: "",
  createdDate: "",
  lastUpdatedDate: "",
  name: "",
  level: 1,
  xp: 0,
  charClass: "",
  background: "",
  currentHP: 0,
  maxHP: 0,
  hitDie: "1d4",
  hitDiceNum: 1,
  dmgDie: "1d4",
  armorDice: 0,
  inventory: "",
  spells: [],
  str: 0,
  dex: 0,
  con: 0,
  int: 0,
  wis: 0,
  cha: 0,
  description: "",
  coins: 0
};
